export const rawProducts = [
  // --- APPLE ---
  {
    sku: "APL-IP17PM-256",
    name: "iPhone 17 Pro Max",
    price: 26999000,
    stock: 15,
    categorySlug: "smartphone",
    brandSlug: "apple",
    img: "/images/ip17pm.webp",
    specs: [
      { n: "Chipset", v: "Apple A19 Pro" },
      { n: "RAM", v: "12 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "APL-IP17P-256",
    name: "iPhone 17 Pro",
    price: 22999000,
    stock: 20,
    categorySlug: "smartphone",
    brandSlug: "apple",
    img: "/images/ip17p.webp",
    specs: [
      { n: "Chipset", v: "Apple A19 Pro" },
      { n: "RAM", v: "12 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "APL-IP17-128",
    name: "iPhone 17",
    price: 16999000,
    stock: 35,
    categorySlug: "smartphone",
    brandSlug: "apple",
    img: "/images/ip17.webp",
    specs: [
      { n: "Chipset", v: "Apple A18 Bionic" },
      { n: "RAM", v: "8 GB" },
      { n: "Penyimpanan", v: "128 GB" },
    ],
  },
  {
    sku: "APL-IP16PM-256",
    name: "iPhone 16 Pro Max",
    price: 23999000,
    stock: 10,
    categorySlug: "smartphone",
    brandSlug: "apple",
    img: "/images/ip16pm.webp",
    specs: [
      { n: "Chipset", v: "Apple A18 Pro" },
      { n: "RAM", v: "8 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "APL-IP16-128",
    name: "iPhone 16",
    price: 14999000,
    stock: 40,
    categorySlug: "smartphone",
    brandSlug: "apple",
    img: "/images/ip16.webp",
    specs: [
      { n: "Chipset", v: "Apple A17 Bionic" },
      { n: "RAM", v: "8 GB" },
      { n: "Penyimpanan", v: "128 GB" },
    ],
  },
  {
    sku: "APL-IP15-128",
    name: "iPhone 15",
    price: 11999000,
    stock: 50,
    categorySlug: "smartphone",
    brandSlug: "apple",
    img: "/images/ip15.webp",
    specs: [
      { n: "Chipset", v: "Apple A16 Bionic" },
      { n: "RAM", v: "6 GB" },
      { n: "Penyimpanan", v: "128 GB" },
    ],
  },
  {
    sku: "APL-IPSE4-128",
    name: "iPhone SE (4th Gen)",
    price: 8999000,
    stock: 20,
    categorySlug: "smartphone",
    brandSlug: "apple",
    img: "/images/ipse4.webp",
    specs: [
      { n: "Chipset", v: "Apple A16 Bionic" },
      { n: "RAM", v: "6 GB" },
      { n: "Penyimpanan", v: "128 GB" },
    ],
  },

  // --- SAMSUNG ---
  {
    sku: "SMG-S24U-256",
    name: "Samsung Galaxy S24 Ultra",
    price: 21999000,
    stock: 25,
    categorySlug: "smartphone",
    brandSlug: "samsung",
    img: "/images/s24u.webp",
    specs: [
      { n: "Chipset", v: "Snapdragon 8 Gen 3" },
      { n: "RAM", v: "12 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "SMG-S24P-256",
    name: "Samsung Galaxy S24+",
    price: 16999000,
    stock: 20,
    categorySlug: "smartphone",
    brandSlug: "samsung",
    img: "/images/s24p.webp",
    specs: [
      { n: "Chipset", v: "Exynos 2400" },
      { n: "RAM", v: "12 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "SMG-S24-256",
    name: "Samsung Galaxy S24",
    price: 13999000,
    stock: 30,
    categorySlug: "smartphone",
    brandSlug: "samsung",
    img: "/images/s24.webp",
    specs: [
      { n: "Chipset", v: "Exynos 2400" },
      { n: "RAM", v: "8 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "SMG-ZFD6-512",
    name: "Samsung Galaxy Z Fold 6",
    price: 27999000,
    stock: 8,
    categorySlug: "smartphone",
    brandSlug: "samsung",
    img: "/images/zfold6.webp",
    specs: [
      { n: "Chipset", v: "Snapdragon 8 Gen 3" },
      { n: "RAM", v: "12 GB" },
      { n: "Penyimpanan", v: "512 GB" },
    ],
  },
  {
    sku: "SMG-ZFL6-256",
    name: "Samsung Galaxy Z Flip 6",
    price: 16999000,
    stock: 15,
    categorySlug: "smartphone",
    brandSlug: "samsung",
    img: "/images/zflip6.webp",
    specs: [
      { n: "Chipset", v: "Snapdragon 8 Gen 3" },
      { n: "RAM", v: "8 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "SMG-S23U-256",
    name: "Samsung Galaxy S23 Ultra",
    price: 17999000,
    stock: 12,
    categorySlug: "smartphone",
    brandSlug: "samsung",
    img: "/images/s23u.webp",
    specs: [
      { n: "Chipset", v: "Snapdragon 8 Gen 2" },
      { n: "RAM", v: "12 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "SMG-S23FE-256",
    name: "Samsung Galaxy S23 FE",
    price: 8499000,
    stock: 40,
    categorySlug: "smartphone",
    brandSlug: "samsung",
    img: "/images/s23fe.webp",
    specs: [
      { n: "Chipset", v: "Exynos 2200" },
      { n: "RAM", v: "8 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "SMG-A55-256",
    name: "Samsung Galaxy A55 5G",
    price: 5999000,
    stock: 60,
    categorySlug: "smartphone",
    brandSlug: "samsung",
    img: "/images/a55.webp",
    specs: [
      { n: "Chipset", v: "Exynos 1480" },
      { n: "RAM", v: "8 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "SMG-A35-256",
    name: "Samsung Galaxy A35 5G",
    price: 4999000,
    stock: 55,
    categorySlug: "smartphone",
    brandSlug: "samsung",
    img: "/images/a35.webp",
    specs: [
      { n: "Chipset", v: "Exynos 1380" },
      { n: "RAM", v: "8 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "SMG-A15-128",
    name: "Samsung Galaxy A15",
    price: 2899000,
    stock: 80,
    categorySlug: "smartphone",
    brandSlug: "samsung",
    img: "/images/a15.webp",
    specs: [
      { n: "Chipset", v: "Helio G99" },
      { n: "RAM", v: "8 GB" },
      { n: "Penyimpanan", v: "128 GB" },
    ],
  },

  // --- XIAOMI ---
  {
    sku: "XIA-14-256",
    name: "Xiaomi 14",
    price: 11999000,
    stock: 20,
    categorySlug: "smartphone",
    brandSlug: "xiaomi",
    img: "/images/xiaomi14.webp",
    specs: [
      { n: "Chipset", v: "Snapdragon 8 Gen 3" },
      { n: "RAM", v: "12 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "XIA-13T-256",
    name: "Xiaomi 13T",
    price: 6499000,
    stock: 40,
    categorySlug: "smartphone",
    brandSlug: "xiaomi",
    img: "/images/xiaomi13t.webp",
    specs: [
      { n: "Chipset", v: "Dimensity 8200 Ultra" },
      { n: "RAM", v: "12 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "XIA-RN13P-256",
    name: "Redmi Note 13 Pro 5G",
    price: 4399000,
    stock: 65,
    categorySlug: "smartphone",
    brandSlug: "xiaomi",
    img: "/images/rn13pro.webp",
    specs: [
      { n: "Chipset", v: "Snapdragon 7s Gen 2" },
      { n: "RAM", v: "8 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "XIA-RN13-128",
    name: "Redmi Note 13",
    price: 2799000,
    stock: 85,
    categorySlug: "smartphone",
    brandSlug: "xiaomi",
    img: "/images/rn13.webp",
    specs: [
      { n: "Chipset", v: "Snapdragon 685" },
      { n: "RAM", v: "8 GB" },
      { n: "Penyimpanan", v: "128 GB" },
    ],
  },
  {
    sku: "XIA-POCOX6P-256",
    name: "POCO X6 Pro 5G",
    price: 4999000,
    stock: 45,
    categorySlug: "smartphone",
    brandSlug: "xiaomi",
    img: "/images/pocox6pro.webp",
    specs: [
      { n: "Chipset", v: "Dimensity 8300 Ultra" },
      { n: "RAM", v: "12 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "XIA-POCOM6P-256",
    name: "POCO M6 Pro",
    price: 2999000,
    stock: 55,
    categorySlug: "smartphone",
    brandSlug: "xiaomi",
    img: "/images/pocom6pro.webp",
    specs: [
      { n: "Chipset", v: "Helio G99 Ultra" },
      { n: "RAM", v: "8 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },

  // --- ASUS ---
  {
    sku: "ASU-ROG8P-512",
    name: "ASUS ROG Phone 8 Pro",
    price: 19999000,
    stock: 10,
    categorySlug: "smartphone",
    brandSlug: "asus",
    img: "/images/rog8pro.webp",
    specs: [
      { n: "Chipset", v: "Snapdragon 8 Gen 3" },
      { n: "RAM", v: "16 GB" },
      { n: "Penyimpanan", v: "512 GB" },
    ],
  },
  {
    sku: "ASU-ROG8-256",
    name: "ASUS ROG Phone 8",
    price: 14999000,
    stock: 15,
    categorySlug: "smartphone",
    brandSlug: "asus",
    img: "/images/rog8.webp",
    specs: [
      { n: "Chipset", v: "Snapdragon 8 Gen 3" },
      { n: "RAM", v: "12 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },
  {
    sku: "ASU-ZF11U-256",
    name: "ASUS Zenfone 11 Ultra",
    price: 12999000,
    stock: 12,
    categorySlug: "smartphone",
    brandSlug: "asus",
    img: "/images/zf11u.webp",
    specs: [
      { n: "Chipset", v: "Snapdragon 8 Gen 3" },
      { n: "RAM", v: "12 GB" },
      { n: "Penyimpanan", v: "256 GB" },
    ],
  },

  // --- AUDIO & TWS ---
  {
    sku: "APL-APP2-C",
    name: "AirPods Pro (2nd Gen) USB-C",
    price: 3999000,
    stock: 40,
    categorySlug: "aksesoris",
    brandSlug: "apple",
    img: "/images/app2.webp",
    specs: [
      { n: "Konektivitas", v: "Bluetooth 5.3" },
      { n: "Fitur", v: "ANC & Transparency" },
    ],
  },
  {
    sku: "APL-AP3-L",
    name: "AirPods (3rd Gen)",
    price: 2999000,
    stock: 35,
    categorySlug: "aksesoris",
    brandSlug: "apple",
    img: "/images/ap3.webp",
    specs: [
      { n: "Konektivitas", v: "Bluetooth 5.0" },
      { n: "Fitur", v: "Spatial Audio" },
    ],
  },
  {
    sku: "SMG-GB2P",
    name: "Samsung Galaxy Buds2 Pro",
    price: 2799000,
    stock: 45,
    categorySlug: "aksesoris",
    brandSlug: "samsung",
    img: "/images/gbuds2p.webp",
    specs: [
      { n: "Konektivitas", v: "Bluetooth 5.3" },
      { n: "Fitur", v: "Intelligent ANC" },
    ],
  },
  {
    sku: "SMG-GBFE",
    name: "Samsung Galaxy Buds FE",
    price: 1399000,
    stock: 60,
    categorySlug: "aksesoris",
    brandSlug: "samsung",
    img: "/images/gbudsfe.webp",
    specs: [
      { n: "Konektivitas", v: "Bluetooth 5.2" },
      { n: "Fitur", v: "Active Noise Cancellation" },
    ],
  },
  {
    sku: "XIA-B4P",
    name: "Xiaomi Buds 4 Pro",
    price: 2499000,
    stock: 25,
    categorySlug: "aksesoris",
    brandSlug: "xiaomi",
    img: "/images/xbuds4p.webp",
    specs: [
      { n: "Konektivitas", v: "Bluetooth 5.3" },
      { n: "Fitur", v: "Hi-Res Audio Wireless" },
    ],
  },

  // --- CHARGER & KABEL ---
  {
    sku: "APL-CHG-20W",
    name: "Apple 20W USB-C Power Adapter",
    price: 449000,
    stock: 100,
    categorySlug: "audio-tws",
    brandSlug: "apple",
    img: "/images/apl20w.webp",
    specs: [
      { n: "Daya Output", v: "20W" },
      { n: "Konektor", v: "USB-C" },
    ],
  },
  {
    sku: "SMG-CHG-45W",
    name: "Samsung 45W Power Adapter",
    price: 499000,
    stock: 80,
    categorySlug: "audio-tws",
    brandSlug: "samsung",
    img: "/images/smg45w.webp",
    specs: [
      { n: "Daya Output", v: "45W" },
      { n: "Konektor", v: "USB-C" },
    ],
  },
  {
    sku: "ANK-CHG-65W",
    name: "Anker 735 Charger (Nano II 65W)",
    price: 699000,
    stock: 40,
    categorySlug: "audio-tws",
    brandSlug: "anker",
    img: "/images/ank65w.webp",
    specs: [
      { n: "Daya Output", v: "65W" },
      { n: "Konektor", v: "2x USB-C, 1x USB-A" },
    ],
  },
  {
    sku: "ANK-CHG-20W",
    name: "Anker 511 Charger (Nano Pro)",
    price: 249000,
    stock: 90,
    categorySlug: "audio-tws",
    brandSlug: "anker",
    img: "/images/ank20w.webp",
    specs: [
      { n: "Daya Output", v: "20W" },
      { n: "Konektor", v: "USB-C" },
    ],
  },
  {
    sku: "XIA-CHG-67W",
    name: "Xiaomi 67W Charging Combo",
    price: 349000,
    stock: 60,
    categorySlug: "audio-tws",
    brandSlug: "xiaomi",
    img: "/images/xia67w.webp",
    specs: [
      { n: "Daya Output", v: "67W" },
      { n: "Konektor", v: "USB-A" },
    ],
  },
  {
    sku: "APL-CBL-C2C",
    name: "Apple USB-C Woven Cable (1m)",
    price: 349000,
    stock: 150,
    categorySlug: "audio-tws",
    brandSlug: "apple",
    img: "/images/aplc2c.webp",
    specs: [
      { n: "Panjang", v: "1 Meter" },
      { n: "Konektor", v: "USB-C to USB-C" },
    ],
  },

  // --- CASING ---
  {
    sku: "SPG-CS-IP17PM",
    name: "Spigen Ultra Hybrid - iPhone 17 Pro Max",
    price: 299000,
    stock: 50,
    categorySlug: "audio-tws",
    brandSlug: "spigen",
    img: "/images/spgip17pm.webp",
    specs: [
      { n: "Material", v: "TPU + Polycarbonate" },
      { n: "Fitur", v: "Anti-Yellowing" },
    ],
  },
  {
    sku: "SPG-CS-IP17P",
    name: "Spigen Mag Armor - iPhone 17 Pro",
    price: 399000,
    stock: 40,
    categorySlug: "audio-tws",
    brandSlug: "spigen",
    img: "/images/spgip17p.webp",
    specs: [
      { n: "Material", v: "TPU" },
      { n: "Fitur", v: "MagSafe Compatible" },
    ],
  },
  {
    sku: "SPG-CS-S24U",
    name: "Spigen Tough Armor - Galaxy S24 Ultra",
    price: 459000,
    stock: 35,
    categorySlug: "audio-tws",
    brandSlug: "spigen",
    img: "/images/spgs24u.webp",
    specs: [
      { n: "Material", v: "TPU + PC" },
      { n: "Fitur", v: "Kickstand Built-in" },
    ],
  },
  {
    sku: "SPG-CS-ZFD6",
    name: "Spigen Slim Armor Pro - Z Fold 6",
    price: 999000,
    stock: 15,
    categorySlug: "audio-tws",
    brandSlug: "spigen",
    img: "/images/spgzfd6.webp",
    specs: [
      { n: "Material", v: "TPU + PC" },
      { n: "Fitur", v: "Hinge Protection" },
    ],
  },

  // --- POWERBANK ---
  {
    sku: "ANK-PB-10K",
    name: "Anker PowerCore 10000 PD Redux",
    price: 599000,
    stock: 50,
    categorySlug: "audio-tws",
    brandSlug: "anker",
    img: "/images/ankpb10.webp",
    specs: [
      { n: "Kapasitas", v: "10000 mAh" },
      { n: "Output", v: "25W Fast Charge" },
    ],
  },
  {
    sku: "ANK-PB-20K",
    name: "Anker 525 Power Bank (PowerCore 20K)",
    price: 999000,
    stock: 30,
    categorySlug: "audio-tws",
    brandSlug: "anker",
    img: "/images/ankpb20.webp",
    specs: [
      { n: "Kapasitas", v: "20000 mAh" },
      { n: "Output", v: "20W PD" },
    ],
  },
  {
    sku: "ANK-PB-MAG5",
    name: "Anker 622 Magnetic Battery (MagGo)",
    price: 899000,
    stock: 40,
    categorySlug: "audio-tws",
    brandSlug: "anker",
    img: "/images/ankmaggo.webp",
    specs: [
      { n: "Kapasitas", v: "5000 mAh" },
      { n: "Fitur", v: "Magnetic Wireless" },
    ],
  },
  {
    sku: "XIA-PB-10K",
    name: "Xiaomi 10000mAh Power Bank 3",
    price: 249000,
    stock: 80,
    categorySlug: "audio-tws",
    brandSlug: "xiaomi",
    img: "/images/xiapb10.webp",
    specs: [
      { n: "Kapasitas", v: "10000 mAh" },
      { n: "Output", v: "18W Fast Charge" },
    ],
  },
  {
    sku: "XIA-PB-20K",
    name: "Xiaomi 20000mAh Power Bank 3 Pro",
    price: 499000,
    stock: 60,
    categorySlug: "audio-tws",
    brandSlug: "xiaomi",
    img: "/images/xiapb20.webp",
    specs: [
      { n: "Kapasitas", v: "20000 mAh" },
      { n: "Output", v: "45W Laptop Charging" },
    ],
  },
];
